server:
  # dev profile port
  port: 8081
  # UTF-8 사용
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  #DB 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/themoment?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  ### JPA 설정 ###
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: create
    show-sql: true

  #Message 설정
  messages:
    basename: i18n/exception
    encoding: UTF-8

  jwt:
    secret: asdkfhksldjhfkajsdhfasd7df67sa8d6f87as6df86sa8d7f6a8ds6f87a9s6d8f76sad87f687ad6f8asd76f8asd6f8asd6f87sd6f87asd6f87s

### Logging ###
logging:
  level:
    org.hibernate.type.descriptor.sql : trace