server:
  # dev profile port
  port: 8081
  # UTF-8 사용
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 10080 # 60m * 24h * 7d = 일주일
      cookie:
        max-age: 10080 # 60m * 24h * 7d
        http-only: true # JSESSIONID 탈취 방지
        name: SID
        secure: true # HTTPS 일때만 쿠키를 전송

spring:
  #H2 DataBase
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  #DB 설정
  datasource:
    url: jdbc:h2:tcp://localhost/~/the-moment
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  #Message 설정
  messages:
    basename: i18n/exception
    encoding: UTF-8

  jwt:
    secret: asdkfhksldjhfkajsdhfasd7df67sa8d6f87as6df86sa8d7f6a8ds6f87a9s6d8f76sad87f687ad6f8asd76f8asd6f8asd6f87sd6f87asd6f87s